p8105_hw2_ltc2121
================

## Problem 1

Data input

``` r
nyc_subway = read_csv("hw2_data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

The variables in the dataset are line, station_name, station_latitude,
station_longitude, route1, route2, route3, route4, route5, route6,
route7, route8, route9, route10, route11, entry, exit_only, vending,
entrance_type, ada. The data has 1868 rows and 20 columns.Since the data
has been imported and selected for the variables of interest. The names
have been standardized with the janitor clean names function. The
variable type has also be changes for several of the variables. Overall
the data is not completely tidy because it is in a wide format. To
convert to a longer dataframe, route could be one variable with the
route number as the value.

``` r
nyc_subway %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

There are 465 distinct stations.

``` r
nyc_subway %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

There are 84 subway stations that are ADA comliant.

``` r
nyc_subway %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

The proportion of station entrances / exits without vending that allow
entrance are 0.377.

``` r
nyc_subway %>% 
  pivot_longer(
    route1:route11, 
    names_to = "route_num", 
    values_to = "route") %>% 
    filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
nyc_subway %>% 
   pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

There are 60 distinct stations serve the A train and of those stations
only 17 are ADA compliant.

## Problem 2

Data input

``` r
trash_wheel = read_excel("hw2_data/Trash Wheel Collection Data.xlsx", 
                         sheet = "Mr. Trash Wheel", 
                         col_types = 
                          c("guess","guess","guess","guess","guess","guess","guess","guess","guess",
                            "guess","guess","guess","guess","guess", "skip", "skip")) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster))  %>% 
  mutate(sports_balls = round(sports_balls),
         num = 1, 
         year = as.numeric(year))

pro_trash_wheel = read_excel("hw2_data/Trash Wheel Collection Data.xlsx", 
                         sheet = "Professor Trash Wheel") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(wheel_num = 1)

all_trash = bind_rows(pro_trash_wheel, trash_wheel)

all_trash %>% 
  arrange(year) 
```

    ## # A tibble: 641 × 16
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 631 more rows, 8 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, wheel_num <dbl>, sports_balls <dbl>, num <dbl>, and
    ## #   abbreviated variable names ¹​volume_cubic_yards, ²​plastic_bottles,
    ## #   ³​polystyrene

``` r
all_trash %>% 
  arrange(desc(year))
```

    ## # A tibble: 641 × 16
    ##    dumpster month     year date                weight_…¹ volum…² plast…³ polys…⁴
    ##       <dbl> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1       86 January   2022 2022-01-05 00:00:00      1.32      15    2700     300
    ##  2       87 February  2022 2022-02-21 00:00:00      0.93      10    3000     420
    ##  3       88 March     2022 2022-03-25 00:00:00      2.01      15    4100     380
    ##  4       89 April     2022 2022-04-07 00:00:00      2.61      15    3900     280
    ##  5       90 May       2022 2022-05-05 00:00:00      3.46      15    4400     500
    ##  6       91 June      2022 2022-06-10 00:00:00      2.76      15    4900     420
    ##  7       92 June      2022 2022-06-21 00:00:00      2.41      10    3600     300
    ##  8       93 July      2022 2022-07-05 00:00:00      2.43      15    4500     400
    ##  9       94 July      2022 2022-07-18 00:00:00      2.98      15    5000     320
    ## 10      511 January   2022 2022-01-05 00:00:00      2.2       15    2700     220
    ## # … with 631 more rows, 8 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, wheel_num <dbl>, sports_balls <dbl>, num <dbl>, and
    ## #   abbreviated variable names ¹​weight_tons, ²​volume_cubic_yards,
    ## #   ³​plastic_bottles, ⁴​polystyrene

``` r
pro_total <- all_trash %>% 
  filter(wheel_num == 2) %>% 
  summarise(sum(weight_tons))

sballs <- trash_wheel %>% 
  filter(year == 2020) %>% 
      summarise(sum(sports_balls))
```

The variables in the dataframe with both Mr. Trash Wheel and Professor
Trash Wheel are dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, grocery_bags, chip_bags, homes_powered, wheel_num,
sports_balls, num. The dataframe has a total of 641 observations. The
years that trash was collected range from 2014 to 2022. From the current
data, the total amount of trash collected by Professor Trash Wheel is 0
tons. The total number of sports balls collected by Mr. Trash Wheel in
2020 was 856 balls.

## Problem 3

Tidy of the pols_month data

``` r
pols_month = read_csv("hw2_data/pols-month.csv") %>% 
  separate(col = mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(month = as.numeric(month), 
         month = month.abb[month], 
         prez_gop = if_else(prez_gop > 0, "gop", NA_character_), 
         prez_dem = if_else(prez_dem > 0, "dem", NA_character_), 
         year = as.numeric(year)) %>% 
   pivot_longer(
    c(prez_gop, prez_dem), 
    names_to = "rid", 
    values_to = "president") %>%  
  filter(!is.na(president)) %>%   
  select(-c(rid, day))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Tidy of the snp data

``` r
snp_df = read_csv("hw2_data/snp.csv") %>% 
  separate(col = date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(year = as.numeric(year), 
         year = if_else(year > 22, (year + 1900), 
                        if_else(year <= 22, (year + 2000) , NA_real_))) %>% 
  mutate(month = as.numeric(month), 
         month = month.abb[month]) %>% 
  select(-day) %>% 
  select(year, month, close)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Tidy of the unemployment data

``` r
unemployment_df = read_csv("hw2_data/unemployment.csv") %>% 
  pivot_longer(
    Jan:Dec, 
    names_to = "month", 
    values_to = "perc_unemployment"
  ) %>% 
  janitor::clean_names()
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Joining the Dataframes

``` r
pm_snp = full_join(pols_month, snp_df, by = c("year", "month"))

full_join_3 = full_join(pm_snp, unemployment_df, by = c("year", "month"))
```
